---
# tasks file for ec2
- name: Installing boto & boto3 on local system
  pip:
    name: "{{ item }}"
    state: present
  loop: "{{ python_pkgs }}"

- name: Creating Security Group for Hadoop Cluster
  ec2_group:
    name: "{{ sg_name }}"
    description: Security Group for Hadoop Cluster with custom rules
    region: "{{ region_name }}"
    aws_access_key: "{{ access_key }}"
    aws_secret_key: "{{ secret_key }}"
    rules:
      - proto: all
        group_name: "{{ sg_name }}"
        rule_desc: allow all traffic from instances connected to this security group
      - proto: tcp
        ports:
        - 22
        cidr_ip: 0.0.0.0/0
        rule_desc: allow all on port 22
    rules_egress:
      - proto: all
        cidr_ip: 0.0.0.0/0
        rule_desc: allow all outbound traffic

- name: Launching four EC2 instances on AWS
  ec2:
    key_name: "{{ keypair }}"
    instance_type: "{{ instance_flavour }}"
    image: "{{ ami_id }}"
    wait: true
    group: "{{ sg_name }}"
    count: 1
    vpc_subnet_id: "{{ subnet_name }}"
    assign_public_ip: yes
    region: "{{ region_name }}"
    state: present
    aws_access_key: "{{ access_key }}"
    aws_secret_key: "{{ secret_key }}"
    instance_tags:
      Name: "{{ item }}"
  register: ec2
  loop: "{{ instance_tag }}"

- name: Add 1st instance to host group namenode
  add_host:
    hostname: "{{ ec2.results[0].instances[0].public_ip }}"
    groupname: namenode

- name: Add 2nd instance to host group datanode
  add_host:
    hostname: "{{ ec2.results[1].instances[0].public_ip }}"
    groupname: datanode

- name: Add 3rd instance to host group datanode
  add_host:
    hostname: "{{ ec2.results[2].instances[0].public_ip }}"
    groupname: datanode

- name: Add 4th instance to host group datanode
  add_host:
    hostname: "{{ ec2.results[3].instances[0].public_ip }}"
    groupname: datanode

- name: Add 5th instance to host group clientnode
  add_host:
    hostname: "{{ ec2.results[4].instances[0].public_ip }}"
    groupname: clientnode

- name: Add 6th instance to host group jobnode
  add_host:
    hostname: "{{ ec2.results[5].instances[0].public_ip }}"
    groupname: jobnode

- name: Add 7th instance to host group tasknode
  add_host:
    hostname: "{{ ec2.results[6].instances[0].public_ip }}"
    groupname: tasknode

- name: Add 8th instance to host group tasknode
  add_host:
    hostname: "{{ ec2.results[7].instances[0].public_ip }}"
    groupname: tasknode

- name: Add 9th instance to host group tasknode
  add_host:
    hostname: "{{ ec2.results[8].instances[0].public_ip }}"
    groupname: tasknode


- name: Wait for SSH to come up
  wait_for:
    host: "{{ ec2.results[0].instances[0].public_dns_name }}"
    port: 22
    state: started
