---
# tasks file for hadoop_jobtracker
- name: Download Java Software
  get_url:
    url: https://mirrors.huaweicloud.com/java/jdk/8u171-b11/jdk-8u171-linux-x64.rpm
    dest: /root/java.rpm

- name: Download Hadoop Software
  get_url:
    url: https://archive.apache.org/dist/hadoop/core/hadoop-1.2.1/hadoop-1.2.1-1.x86_64.rpm
    dest: /root/hadoop.rpm
 
- name: Install Packages
  command : "rpm -i /root/{{ item }} --force"
  loop: "{{ pkgs_name }}"

- name: Configure core-site file 
  template:
    src: "core-site.xml.j2"
    dest: "/etc/hadoop/core-site.xml"

- name: Configure mapred-site file
  template:
    src: "mapred-site.xml.j2"
    dest: "/etc/hadoop/mapred-site.xml"

- name: Starting jobtracker service
  shell: "hadoop-daemon.sh start jobtracker"